dist: xenial

language: node_js
node_js:
  - "12"

# Install specific version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --non-interactive

script:
  - yarn test --ci --verbose
  - yarn run build

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION

# Monitor only these branches
branches:
  only:
  - master
  - dev

# $HOME/.cache/yarn
cache:
  yarn: true


# https://docs.travis-ci.com/user/deployment/pages/
before_deploy:
- npm run docs
- echo '# Live examples' > docs/README.md

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch:  'gh-pages'
  local-dir:  'docs'
  on:
    branch: 'master'
