name: build

on:
  push:
    branches:
      - master
      - dev
      - 8.x
  pull_request:
    branches:
      - master
      - dev
      - 8.x
  schedule:
    - cron: '0 0 11 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: npm run test
      - run: bash <(curl -s https://codecov.io/bash)
      - run: npm run build
      - run: npm run docs

      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: docs
          single-commit: true
          clean: true
